name: Build project

on:
  push:
    tags-ignore:
      - 'v*'
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler-version: ["9", "10"]
        app: ["Dummy0", "Dummy1"]
        processor: ["STM32F407VG", "STM32F407ZG"]
    container: marekmosna/arm32v7-none-eabi-toolchain:${{ matrix.compiler-version }}
    env:
      BINARY_DIR: build-gcc-v${{ matrix.compiler-version }}
      TARGET: ${{ matrix.app }}_${{ matrix.processor }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: CMake configure project
        run: cmake -DCMAKE_TOOLCHAIN_FILE="cmake/arm-gcc-toolchain.cmake" -S . -B ${{ env.BINARY_DIR }}

      - name: Build project
        run: cmake --build ${{ env.BINARY_DIR }} --target ${{ env.TARGET }}

      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.TARGET }}-app-gcc-v${{ matrix.compiler-version }}
          path: ${{ env.BINARY_DIR }}/apps/${{ env.TARGET }}
