name: Releases

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler-version: ["8", "9", "10"]
    container: marekmosna/arm32v7-toolchain:${{ matrix.compiler-version }}
    env:
      BINARY_DIR: build
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: CMake configure project
        run: cmake -DCMAKE_TOOLCHAIN_FILE="cmake/arm-gcc-toolchain.cmake" -S . -B ${{ env.BINARY_DIR }}

      - name: Build project
        run: cmake --build ${{ env.BINARY_DIR }} --target Dummy

      - name: Name output
        run: cp ${{ env.BINARY_DIR }}/apps/Dummy ${{ env.BINARY_DIR }}/apps/dummy-app-gcc-v${{ matrix.compiler-version }}

      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: dummy-app-gcc-v${{ matrix.compiler-version }}
          path: ${{ env.BINARY_DIR }}/apps/dummy-app-gcc-v${{ matrix.compiler-version }}
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Download artefacts
        uses: actions/download-artifact@v2

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: docs/CHANGELOG_${{ steps.get_version.outputs.VERSION }}.md
          tag: ${{ steps.get_version.outputs.VERSION }}
          name: Release ${{ steps.get_version.outputs.VERSION }}
          artifacts: "dummy-app-gcc*/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
