name: Run project unit-tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BINARY_DIR: build
    steps:
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Checkout project
        uses: actions/checkout@v2

      - name: Configure project
        run: docker run --rm --platform linux/arm/v7 --privileged -v $PWD:/work marekmosna/arm32v7-runtime:latest cmake -S . -B ${{ env.BINARY_DIR }}

      - name: Build tests
        run: docker run --rm --platform linux/arm/v7 --privileged -v $PWD:/work marekmosna/arm32v7-runtime:latest cmake --build ${{ env.BINARY_DIR }} --target all

      - name: Run tests
        run: docker run --rm --platform linux/arm/v7 --privileged -v $PWD:/work marekmosna/arm32v7-runtime:latest cmake --build ${{ env.BINARY_DIR }} --target test

      - name: Archive log
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-log
          path: ${{ env.BINARY_DIR }}/Testing/Temporary/LastTest.log
