name: Dummy

on:
  workflow_dispatch:
    branches: [ '**' ]

jobs:
  runtime:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm

      - name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}

      - name: Update
        run: docker run --rm --platform linux/arm/v7 arm32v7/ubuntu:latest apt update
