name: Dummy

on:
  workflow_dispatch:
    branches: [ '**' ]

jobs:
  runtime:
    runs-on: ubuntu-latest
    steps:
      - name: Update
        run: docker run --rm --platform linux/arm/v7 arm32v7/ubuntu:latest apt update
